name: Automation Tests

on:
  push:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and capture summary
        run: |
          npx cypress run --spec "testscripts/*" | tee cypress-summary.txt

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ github.sha }}
          path: cypress/videos/
          retention-days: 7

      - name: Upload Test Summary Log
        uses: actions/upload-artifact@v4
        with:
          name: cypress-summary-${{ github.sha }}
          path: cypress-summary.txt
          retention-days: 7
